set(CPM_WS_VERSION "5f52b7d3d287c1b2ebe0ea3bf68b0f987395e19a" CACHE PATH "")

if(NOT DEFINED CPM_WS_SOURCE_DIR)
	if(NOT DEFINED CPM_WS_VERSION)
		message(FATAL_ERROR "CPM_WS_VERSION must be defined")
	endif()
	
	CPMAddPackage(
	  NAME cpm_ws_src
	  GIT_TAG ${CPM_WS_VERSION}
	  GITHUB_REPOSITORY loopunit/cpm_ws
	  DOWNLOAD_ONLY)

	set(CPM_SOURCE_CACHE "${CMAKE_CURRENT_BINARY_DIR}/.cpm_src" CACHE PATH "")
	set(CPM_WS_SOURCE_DIR "${cpm_ws_src_SOURCE_DIR}" CACHE PATH "")
	set(CPM_WS_INSTALL_CACHE "${CMAKE_CURRENT_BINARY_DIR}/.cpm_install" CACHE PATH "")
	set(CPM_WS_SOURCE_CACHE "${CMAKE_CURRENT_BINARY_DIR}/.cpm_src" CACHE PATH "")
	set(CPM_WS_BUILD_CACHE "${CMAKE_CURRENT_BINARY_DIR}/.cpm_out" CACHE PATH "")
	set(CPM_WS_DEV_ROOT "${CMAKE_CURRENT_BINARY_DIR}" CACHE PATH "")
endif()

include(${CPM_WS_SOURCE_DIR}/cmake/cpm_ws.cmake)
